### ISSUE TITLE
Publish to AUR?

### ISSUE THREAD

**Issue by colemickens** [eyelash/xi-gtk#6]
https://github.com/eyelash/xi-gtk/tree/PKGBUILD

Can you publish those to the AUR?

**Comment by eyelash** [comment]
The reason I didn't publish them to the AUR is because I'm quite new to Arch packaging and I wasn't sure if there were some obvious mistakes in my PKGBUILDs. Also the [rules](https://wiki.archlinux.org/index.php/Arch_User_Repository#Rules_of_submission) say only useful should be uploaded and xi-gtk in its current state is not really ready yet to be used as an editor.
But I will upload them as soon as I find the time because there seems to be demand for it.

**Comment by eyelash** [comment]
[done](https://aur.archlinux.org/packages/xi-gtk-git/)
